其他2/day06/app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path

from app.views import *

urlpatterns = [
    path('index/', index),
    # 跳转，无参情况
    path('redirect_no_params/', redirect1, name='no_params'),
    # 跳转，有参情况
    path('redirect_params/<int:id>/', redirect2, name='params'),
    re_path('redirect_params2/(\d+)/', redirect2, name='params2'),
    # 请求
    path('index2/', index2),

    # 权限
    # path('add_permission/', login_required(add_permission)),
    path('add_permission/', add_permission),
    path('menu/', menu),

]

其他2/day06/day04/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from day04.settings import MEDIA_URL, MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    # 路由分发
    # django2.0以下版本
    # url('app/', include('app.urls', namespace='app')),
    path('app/', include(('app.urls', 'app'), namespace='app')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

其他2/day06/user/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from user.views import register, login, logout, index, \
    my_register, my_login, my_index, my_session_login, my_session_logout, \
    register_icon, list_user

urlpatterns = [
    # 使用django自带的User模型实现登录注册注销
    path('register/', register),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('index/', index, name='index'),
    # 自定义User模型，并实现登录注册注销（采用cookie+token的形式）
    path('my_register/', my_register),
    path('my_login/', my_login, name='my_login'),
    path('my_index/', my_index, name='my_index'),
    # 使用session实现登录
    path('my_session_login/', my_session_login, name='my_session_login'),
    path('my_session_logout/', my_session_logout, name='my_session_logout'),
    # 头像上传ImageFiled使用
    path('register_icon/', register_icon),
    # 分页
    path('list/', list_user, name='list'),

]

其他2/day06/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p><img src="/media/{{ user.icon }}"></p>
    <p>跳转、重定向</p>
    <p>id：{{ id }}</p>
    <!--无参情况-->
    <P><a href="/app/redirect_no_params/">重定向地址1</a></P>
    <P><a href="{% url 'app:no_params' %}">重定向地址1</a></P>
    <!--有参情况-->
    {# {% url 'namespace:name' 参数值1 参数值2 参数值3 %} #}
    <P><a href="{% url 'app:params' 15 %}">重定向地址2</a></P>
</body>
</html>

其他2/day06/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table>
        <thead>
            <th>姓名</th>
            <th>头像</th>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td><img src="/media/{{ user.icon }}" width="100" height="100" alt=""></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>
        当前页: {{ users.number }}
        总页码: {{ users.paginator.num_pages }}

        {% if users.has_previous %}
        <a href="{% url 'user:list' %}?page={{ users.previous_page_number }}">上一页</a>
        {% endif %}

        {% for i in users.paginator.page_range %}
            <a href="{% url 'user:list' %}?page={{ i }}">{{ i }}</a>
        {% endfor %}

        {% if users.has_next %}
        <a href="{% url 'user:list' %}?page={{ users.next_page_number }}">下一页</a>
        {% endif %}
    </p>
</body>
</html>

其他2/day06/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    {{ pwd_error }}
    <form action="" method="post">
        <p>姓名:<input type="text" name="username"> {{ errors.username }}</p>
        <p>密码:<input type="password" name="password"> {{ errors.password }}</p>
        <p><input type="submit" value="提交"></p>
    </form>
</body>
</html>

其他2/day06/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>菜单</title>
</head>
<body>
    {{ perms.newuser }}

    {{ perms.app.sel }}
    {{ perms.app.add }}
    {{ perms.app.delete }}
    {{ perms.app.update }}

    {% if perms.app.add or user.is_superuser %}
        <p>新增用户权限</p>
    {% endif %}

    {% if perms.app.sel or user.is_superuser %}
        <p>查看用户权限</p>
    {% endif %}

    {% if perms.app.delete or user.is_superuser %}
        <p>删除用户权限</p>
    {% endif %}

    {% if perms.app.update or user.is_superuser %}
        <p>修改用户权限</p>
    {% endif %}
</body>
</html>

其他2/day06/templates/perms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分配权限页面</title>
</head>
<body>
    <form action="" method="post">
        <p>当前用户: {{ user }}</p>
        <p>角色:
            <select name="role">
                {% for g in goups %}
                    <option value="{{ g.id }}">{{ g.name }}</option>
                {% endfor %}
            </select>
        </p>
        <p>
            {% for permission in permissions %}
                <input type="checkbox" name="per" value="{{ permission.id }}">{{ permission.name }}
            {% endfor %}
        </p>
        <p><input type="submit" value="提交"></p>
    </form>
</body>
</html>

其他2/day06/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">
        <p>姓名:<input type="text" name="username"> {{ errors.username }}</p>
        <p>密码:<input type="password" name="pwd1"> {{ errors.pwd1 }}</p>
        <p>确认密码:<input type="password" name="pwd2">{{ errors.pwd2 }}</p>
        <p><input type="submit" value="提交"></p>
    </form>
</body>
</html>

其他2/day06/templates/register2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        <p>姓名:<input type="text" name="username"> {{ errors.username }}</p>
        <p>密码:<input type="password" name="pwd1"> {{ errors.pwd1 }}</p>
        <p>确认密码:<input type="password" name="pwd2">{{ errors.pwd2 }}</p>
        <p>头像:<input type="file" name="icon"></p>
        <p><input type="submit" value="提交"></p>
    </form>
</body>
</html>