fresh_shop/carts/urls.py
from django.urls import path

from carts.views import carts, add_carts, remove_carts, update_carts

urlpatterns = [
    path('carts/', carts, name='carts'),
    path('add_carts/', add_carts, name='add_carts'),
    path('update_carts/', update_carts, name='update_carts'),
    path('remove_carts/', remove_carts, name='remove_carts'),


]

fresh_shop/fresh_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include(('user.urls', 'user'), namespace='user')),
    path('goods/',include(('goods.urls', 'goods'), namespace='goods')),
    path('carts/',include(('carts.urls', 'carts'), namespace='carts')),
    path('order/',include(('order.urls', 'order'), namespace='order')),
]

# media 图片访问  添加能当作静态文件自动访问
urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

fresh_shop/goods/urls.py
from django.urls import path

from goods.views import goods_index, goods_detail, goods_list, search

urlpatterns = [
    path('index/', goods_index, name='index'),
    path('list/', goods_list, name='list'),
    path('detail/<int:id>/', goods_detail, name='detail'),
    path('search/', search, name='search'),

]

fresh_shop/order/urls.py
from django.urls import path

from order.views import place_order, submit_order

urlpatterns = [
    path('place_order/', place_order, name='place_order'),
    path('submit_order/', submit_order, name='submit_order')
]

fresh_shop/user/urls.py
from django.urls import path

from user.views import user_center_info, user_center_order, user_center_site, login, register, logout, edit_site

urlpatterns = [
    path('info/', user_center_info, name='info'),
    path('order/', user_center_order, name='order'),
    path('site/', user_center_site, name='site'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit_site/', edit_site, name='edit_site'),
]

fresh_shop/carts/models.py
from django.db import models

# Create your models here.
from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'shopping_cart'

fresh_shop/carts/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from carts.models import ShoppingCart
from goods.models import Goods
from user.models import User

# final_price = 0  # 定义全局变量
def carts(request):
    if request.method == 'GET':
        session_goods = request.session.get('session_goods')   # 从session中获取商品信息
        goods_list = []
        final_price = 0
        if session_goods:
            for g in session_goods:
                goods_id = g[0]
                count = g[1]
                is_select = g[2]
                goods = Goods.objects.filter(id=goods_id).first()
                goods_list.append([goods,count,is_select])
                total_price = count * goods.shop_price  # 小计
                final_price += total_price    # 总价格
        return render(request, 'carts.html', {'goods_list':goods_list, 'final_price': final_price})


# 修改购物车商品数量
def update_carts(request):
 # 修改购物车小计
 #    if request.is_ajax():
    if request.method == 'GET':
        goods_id = int(request.GET.get('goods_id'))
        count = int(request.GET.get('count'))
        goods = Goods.objects.filter(id=goods_id).first()
        total_price = count * goods.shop_price  # 小计
        # 将修改后的数据存入session
        session_goods = request.session.get('session_goods')   # 从session中获取商品信息
        for g in session_goods:
            if g[0] == goods_id:
                g[1] = count    # 存入修改后的商品数量
                request.session['session_goods'] = session_goods

        return JsonResponse({'total_price': total_price})


# 添加商品到购物车
def add_carts(request):
    if request.method == 'GET':
        goods_id = int(request.GET.get('id'))
        count = int(request.GET.get('count'))
        is_select = 0
        # 添加商品到session
        session_goods = request.session.get('session_goods')
        if not session_goods:
            session_goods = []
            request.session['is_sync'] = 0
        else:
            for g in session_goods:
                if g[0] == goods_id:
                    g[1] += count
                    request.session['session_goods'] = session_goods
                    return JsonResponse({'success': '成功添加到购物车'})
        session_goods.append([goods_id, count, is_select])
        request.session['session_goods'] = session_goods
        return JsonResponse({'success': '成功添加到购物车'})


# 删除购物车商品
def remove_carts(request):
    if request.is_ajax():
        goods_id = int(request.GET.get('goods_id'))
        final_price = int(request.GET.get('final_price'))
        goods = Goods.objects.filter(id=goods_id).first()
        session_goods = request.session.get('session_goods')

        for g in session_goods:
            if g[0] == goods_id:
                session_goods.remove(g)     # 删除session中的数据
                request.session['session_goods']=session_goods
                carts = ShoppingCart.objects.filter(goods_id=goods_id).first()
                carts.delete()    # 删除数据库数据
                total_price = goods.shop_price * g[1]
                final_price -= total_price
        return JsonResponse({'success': '删除ok', 'final_price': final_price})

fresh_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}

        {% endblock %}
    </title>

    {% block css %}

    {% endblock %}


    {% block js1 %}

    {% endblock %}

</head>

<body>
{% block header %}

{% endblock %}


{% block content %}

{% endblock %}


{% block footer %}

{% endblock %}


{% block popup %}

{% endblock %}


{% block js2 %}

{% endblock %}

</body>
</html>

fresh_shop/templates/base_main.html
{% extends 'base.html' %}


{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}

{% block js1 %}
<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{% endblock %}

{% block header %}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div id="user" class="login_info fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录 </a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'carts:carts' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:place_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

    <script>
        {#显示用户登陆状态#}
        $(function(){
            if ($('#user em').html()!=''){
                $('div.login_btn.fl').hide()
                $('#user').show()
            }
        })
    </script>
{% endblock %}





{% block footer %}
<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>
{% endblock %}

fresh_shop/templates/carts.html
{% extends 'base_main.html' %}


{% block title %}
天天生鲜-购物车
{% endblock %}


{% block header %}
{{ block.super }}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}


{% block content %}
<div class="total_count">全部商品<em>{{ goods_list | length }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

    {% for g in goods_list %}  {# goos_list :[[goods],[count],[is_select] #}
    <ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="checkbox" value="{{ g.0.id }}" {% if g.2 == 1 %}checked{% endif %}></li>
		<li class="col02"><img src="/media/{{ g.0.goods_front_image }}"></li>
		<li class="col03" value="{{ g.0.id }}">{{ g.0.name }}<br><em>{{ g.0.shop_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ g.0.shop_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ g.1 }}" kucun="{{ g.0.goods_nums }}" >
{#                onkeyup="$('#total').html($(this).val())"#}
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{% widthratio g.0.shop_price 1 g.1 %}元</li>
{#        <span id="{{ forloop.counter }}"> </span>#}

		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" {% if goods_list.0.2 == 1 %}checked{% endif %}></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ final_price }}元</em><br>共计<b>{{ goods_list | length }}</b>件商品</li>
		<li class="col04"><a href="{% url 'order:place_order' %}">去结算</a></li>
	</ul>

    <script>
    $(function () {

        {#---全选---#}
        $('ul.settlements li.col01 input').click(function () {
            if ($(this).prop('checked')){
                $('ul.cart_list_td.clearfix li.col01 input').prop('checked',true)
            }else {
                $('ul.cart_list_td.clearfix li.col01 input').prop('checked',false)
            }
         });

        {#---商品选中状态---#}
        {#function select(is_select){#}
        {#    $.ajax({#}
        {#        type: 'get',#}
        {#        url: '{% url 'carts:carts' %}',#}
        {#        data: {'is_select':is_select },#}
        {#        async: false,#}
        {#        success: function(data) {#}
        {#            console.log(data)#}
        {#        },#}
        {#        error: function (e) {#}
        {#            console.log(e)#}
        {#        }#}
        {#    });#}
        {# }#}
        {#$('ul.cart_list_td.clearfix li.col01 input').click(function () {#}
        {#    if($(this).prop('checked')){#}
        {#        select(1)#}
        {#    }else{#}
        {#        select(0)#}
        {#    }#}
        {# });#}


        {#----------获取最终价格--------#}
        function finalPrice(){
            var final_price = 0;
            for(var i=0; i<$('li.col07').length; i++){
                total_price = parseFloat($('li.col07').eq(i).html());
                final_price += total_price;
            }
            $('ul.settlements li.col03 em').html(final_price+'元')
            return final_price
        }

        {#-----------修改数据----------#}
        {#---获取小计---#}
        var res;
        function totalPrice(count,goods_id) {
            console.log(goods_id)
            $.ajax({
                type: 'get',
                url: '{% url 'carts:update_carts' %}',
                data: {'count':count,'goods_id':goods_id },
                async: false,
                success: function(data) {
                    res = data;
                },
                error: function (e) {
                    console.log(e)
                }
            });
         }

        {#---直接修改输入框数量---#}
        var num=1;
        $('input.num_show.fl').blur(function () {
            var kucun = $(this).attr('kucun');  // 库存
            if ($(this).val()>kucun) {
                $(this).val(kucun);
             }
            if ($(this).val()<1) {
                $(this).val(1);
             }
            num = $(this).val();
            goods_id = $(this).parent().parent().siblings('.col03').val()
            totalPrice(num,goods_id)
            $(this).parent().parent().siblings('.col07').html(res.total_price+'元')
            finalPrice()
         });

        {#---数量增加---#}
        $('a.add.fl').click(function () {
            num = $(this).siblings('input').val();
            var kucun = parseInt($(this).siblings('input').attr('kucun'));  // 库存
            {#console.log(typeof kucun)#}
            if (num<kucun) {
                num++;
                $(this).siblings('input').val(num);
                goods_id = $(this).parent().parent().siblings('.col03').val();
                totalPrice(num,goods_id);
                $(this).parent().parent().siblings('.col07').html(res.total_price+'元');
                finalPrice();
             }
            else{alert('库存不足!')}
        });

        {#---数量减少---#}
        $('a.minus.fl').click(function () {
             num = $(this).siblings('input').val();
            if (num>1){
                num--;
                $(this).siblings('input').val(num);
                goods_id = $(this).parent().parent().siblings('.col03').val()
                totalPrice(num,goods_id);
                $(this).parent().parent().siblings('.col07').html(res.total_price+'元')
                finalPrice()
            }
        });


         {#----------移除商品--------#}
        $('ul.cart_list_td.clearfix li.col08').click(function () {
            console.log('qqqq')
            var goods_id = $(this).siblings('.col03').val();
            var count = $(this).siblings('.col06 input').val()
            var final_price = finalPrice();
            var that = this;
            $.ajax({
                type: 'get',
                url: '{% url 'carts:remove_carts' %}',
                data: {'count':count, 'goods_id':goods_id, 'final_price':final_price },
                async: true,
                success: function(data) {
                    console.log(data.success);
                    $(that).parent().remove()
                    $('ul.settlements li.col03 em').html(data.final_price+'元')
                },
                error: function (e) {
                    console.log(e)
                }
            })
        });


    })
</script>


{% endblock %}

fresh_shop/templates/detail.html
{% extends 'base_main.html' %}


{% block title %}
    天天生鲜-商品详情
{% endblock %}


{% block header %}
    {{ block.super }}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<form action="{% url 'goods:search' %}" method="post">
            {% csrf_token %}
            <input type="text" class="input_text fl" name="name_keyword" placeholder="搜索商品">
            <input type="submit" class="input_btn fr" name="" value="搜索">
        </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'carts:carts' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ my_carts }}</div>
		</div>
	</div>
{% endblock %}


{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="{% url 'goods:list' %}?category=1&page=1" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' %}?category=2&page=1" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' %}?category=3&page=1" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' %}?category=4&page=1" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' %}?category=5&page=1" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' %}?category=6&page=1" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:list' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' %}?category={{ goods.category_id }}">
        {% ifequal goods.category_id 1 %}新鲜水果{% endifequal %}
        {% ifequal goods.category_id 2 %}海鲜水产{% endifequal %}
        {% ifequal goods.category_id 3 %}猪牛羊肉{% endifequal %}
        {% ifequal goods.category_id 4 %}禽类蛋白{% endifequal %}
        {% ifequal goods.category_id 5 %}新鲜蔬菜{% endifequal %}
        {% ifequal goods.category_id 6 %}速冻食品{% endifequal %}
        </a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img width="350" height="350" src="/media/{{ goods.goods_front_image }}"></div>

		<div class="goods_detail_list fr">
            <div id="add" style="display: none;width:300px;height:270px;background:rgba(200,200,200,0.8);position:absolute;">
                <p style="text-align: center; color:green;font-size: 30px;margin-top: 30px"> 恭喜您! </p>
                <p style="text-align: center;color:green;font-size: 30px"></p>
                <div style="text-align: center;margin-top: 80px">
                    <button style="width: 80px;height: 40px;background: #9f9f9f;cursor: pointer">返回详情</button>
                    <a href="{% url 'carts:carts' %}"><button style="width: 80px;height: 40px;background: #9f9f9f;cursor: pointer;margin-left: 50px">去购物车</button></a>
                </div>
            </div>

			<h3>{{ goods.name }}</h3>
			<p>{{ goods.goods_brief }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.shop_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
                <span class="show_unit">库  存：{{ goods.goods_nums }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>

				<div class="num_add fl">
					<input type="text" name="count" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>{{ goods.shop_price }}</em>元</div>
			<div class="operate_btn">
				<a href="" class="buy_btn">立即购买</a>
{#				<a href="" class="add_cart" id="add_cart">加入购物车</a>#}
				<span style="cursor: pointer;" class="add_cart" id="add_cart">加入购物车</span>
			</div>

		</div>

	</div>

    <script>
    $(function () {
        {#-----加入购物车------#}
        function add_carts(){
            var count = $('input.num_show.fl').val();
            $.ajax({
                type: 'get',
                url: '/carts/add_carts/',
                data: {'count':count,'id':{{ goods.id }} },
                async: true,
                success: function(data) {
                    console.log(data.goods_type_count)
                    $('#show_count').html(data.goods_type_count)
                    $('#add p').eq(1).html(data.success)
                    if($('#add p').eq(1).html()!=''){
                        $('#add').show()
                    }

                },
                error: function (e) {
                    console.log(e)
                }
            });
        }

        $('#add_cart').click(function () {
            add_carts()
        });
        $('#add button').eq(0).click(function () {
            $('#add').hide()
        });



        {#-----商品的增加和减少-----#}
        var res;
        function totalPrice() {
            count = $('input.num_show.fl').val();
            $.ajax({
                type: 'get',
                url: '{% url 'goods:detail' goods.id %}',
                data: {'count':count },
                async: false,
                success: function(data) {
                    res = data;
                },
                error: function (e) {
                    console.log(e)
                }
            });
        }
        {#失去焦点#}
        var num=1;
        $('input.num_show.fl').blur(function () {
            if ($('input.num_show.fl').val()>{{ goods.goods_nums }}) {
                $('input.num_show.fl').val({{ goods.goods_nums }});
            }
            if ($('input.num_show.fl').val()<1) {
                $('input.num_show.fl').val(1);
            }
            totalPrice();
            $('div.total em').html(res.total_price)
        });

        {#数量增加#}
        $('a.add.fr').click(function () {
            num = $('input.num_show.fl').val();
            if (num<{{ goods.goods_nums }}){
                num++;
                $('input.num_show.fl').val(num);
                totalPrice();
                $('div.total em').html(res.total_price)
            }
            else{alert('库存不足!')}
        });

        {#数量减少#}
        $('a.minus.fr').click(function () {
             num = $('input.num_show.fl').val();
            if (num>1){
                num--;
                $('input.num_show.fl').val(num);
                totalPrice();
                $('div.total em').html(res.total_price)
            }
        })
    })
    </script>
    
    
	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="/static/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="/static/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc }}</dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}



{% block footer %}
    {{ block.super }}
    <div class="add_jump"></div>
{% endblock %}


{% block js2 %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{#    <script type="text/javascript">#}
{#    var $add_x = $('#add_cart').offset().top;#}
{#    var $add_y = $('#add_cart').offset().left;#}
{##}
{#    var $to_x = $('#show_count').offset().top;#}
{#    var $to_y = $('#show_count').offset().left;#}
{##}
{#    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})#}
{#    $('#add_cart').click(function(){#}
{#        $(".add_jump").stop().animate({#}
{#            'left': $to_y+7,#}
{#            'top': $to_x+7},#}
{#            "fast", function() {#}
{#                $(".add_jump").fadeOut('fast',function(){#}
{#                    $('#show_count').html(2);#}
{#                });#}
{##}
{#        });#}
{#    })#}
{#</script>#}
{% endblock %}

fresh_shop/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

fresh_shop/templates/user_center_info.html
{% extends 'base_main.html' %}


{% block title %}
天天生鲜-用户中心
{% endblock %}



{% block header %}
{{ block.super }}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}


{% block content %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li id="info"><a href="{% url 'user:info' %}" >· 个人信息</a></li>
            <li id="order"><a href="{% url 'user:order' %}">· 全部订单</a></li>
            <li id="site"><a href="{% url 'user:site' %}">· 收货地址</a></li>
        </ul>
    </div>


    {% block user_center_con %}
    <div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>1387555</li>
							<li><span>联系地址：</span>北京市昌平区</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="/static/images/goods/goods003.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods004.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods005.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods006.jpg"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods007.jpg"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
    {% endblock %}

	</div>
{% endblock %}



{% block js2 %}
    {% block js2_child %}
        <script>
            $('#info a').addClass('active').siblings().removeClass('active')
        </script>
    {% endblock %}
{% endblock %}